name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Check for upstream changes
      id: check_upstream
      run: |
        git ls-remote https://github.com/rembo10/headphones.git HEAD > upstream.txt
        echo "hash=$(cat upstream.txt | awk '{ print $1 }')" >> $GITHUB_OUTPUT

    - name: Get last built commit
      id: get_cached_hash
      run: |
        echo "cached_hash=$(cat .upstream_hash 2>/dev/null || echo 'none')" >> $GITHUB_OUTPUT

    - name: Compare hashes
      id: compare
      run: |
        if [ "${{ steps.get_cached_hash.outputs.cached_hash }}" != "${{ steps.check_upstream.outputs.hash }}" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Cache new hash
      if: steps.compare.outputs.changed == 'true'
      run: |
        echo "${{ steps.check_upstream.outputs.hash }}" > .upstream_hash
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .upstream_hash
        git commit -m "Update upstream hash"
        git push

    - name: Log change status
      run: echo "Changed? ${{ steps.compare.outputs.changed }}"

    - name: Build Docker image
      if: steps.compare.outputs.changed == 'true'
      run: |
        docker build -t factualgoldfish/headphones:latest .

    - name: Log in to Docker Hub
      if: steps.compare.outputs.changed == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      if: steps.compare.outputs.changed == 'true'
      run: |
        docker tag factualgoldfish/headphones:latest factualgoldfish/headphones:$(date +%Y%m%d)
        docker push factualgoldfish/headphones:latest
        docker push factualgoldfish/headphones:$(date +%Y%m%d)
